# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# export_method: "app-store",
#       export_options: {
#         provisioningProfiles: { 
#          "com.KlearExpress.customer" => "Klear Express App Store",
#       		"com.KlearExpress.customer.notification" => "Klear Express Notification Extension"
#         }
#       }

default_platform(:ios)

platform :ios do
  
  lane :beta do
    sync_code_signing(type: "appstore")  
     match(
        app_identifier: ["com.KlearExpress.customer","com.KlearExpress.customer.notification"],
        type: "appstore",
    )  
    increment_build_number(xcodeproj: "App.xcodeproj")
    build_app(scheme: "App", clean: true, silent: true)
    upload_to_testflight
   
  end

end
